#!/bin/bash

# Example:

# source <(curl -sL freaks.dev/scripts/bash_spin)
# printf "Hacking NASA    "
# spin &
# spinpid=$!
# trap 'kill $spinpid' SIGTERM SIGKILL
# {
#     # You can run all the command you want here. I will run only sleep command.
#     sleep 5
# } &>/dev/null
# kill $spinpid
# printf "\b \t[Done]\n"
# printf "NASA has been successfully hacked!!!\n"

spin() {
    local i=0
    local sp="/-\|"
    local n=${#sp}
    printf " "
    sleep 0.2
    while true; do
        printf "\b%s" "${sp:i++%n:1}"
        sleep 0.2
    done
}
