#!/bin/bash

if ! [[ $(id -u) = 0 ]]; then
	echo "This script must be run as root!"
	exit 1
fi

title() {
	clear
	echo -ne "
################################################################################
#                                                                              #
#   This is Automated Artix Linux Installer for both UEFI and Legacy System    #
#                                                                              #
#                                    By                                        #
#                                                                              #
#                               Hein Oke Soe                                   #
#                                                                              #
################################################################################

"
}

start_install() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Getting User Inputs
--------------------------------------------------------------------------------

"
	read -srp "root password: " root_password
	echo
	export root_password

	read -rp "username: " username
	export username

	read -srp "password for $username: " user_password
	echo
	export user_password

	read -rp "hostname: " hostname
	export hostname

	choose_disk

	read -rp "Boot partition size: " boot_partition_size
	export boot_partition_size

	read -rp "Root partition size: " root_partition_size
	export root_partition_size

	export timezone="$(curl -s --fail https://ipapi.co/timezone 2>/dev/null)"

	export target_mount_point="/mnt"

	setup_disk
}

choose_disk() {
	echo "Select the disk to install: "
	options=($(lsblk -n --output TYPE,KNAME,SIZE | awk '$1=="disk"{print "/dev/"$2"("$3")"}'))
	select_option $? 1 "${options[@]}"
	export chosen_disk=${options[$?]}
	export target_device=${chosen_disk%(*}
}

check_uefi() {
	title
	if [[ ! -d /sys/firmware/efi ]]; then
		export is_uefi="no"
	fi
}

part_disk() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Creating Partitions
--------------------------------------------------------------------------------

"
	wipefs -a ${target_device}*
	if [[ "$is_uefi" == "no" ]]; then
		sfdisk -q --force --delete "$target_device"
		[[ -b "$target_device" ]] && echo -e ",${boot_partition_size},0c,*\n,${root_partition_size},L," | sfdisk -q --label dos "$target_device"
	else
		sfdisk -q --force --delete "$target_device"
		[[ -b "$target_device" ]] && echo -e ",${boot_partition_size},U,*\n,${root_partition_size},L," | sfdisk -q --label gpt "$target_device"
	fi

}

format_disk() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Formatting Partitions
--------------------------------------------------------------------------------

"

	if [[ "$target_device" =~ "nvme" ]]; then
		export boot_partition="${target_device}p1"
		export root_partition="${target_device}p2"
	else
		export boot_partition="${target_device}1"
		export root_partition="${target_device}2"
	fi

	mkfs.fat -F32 "$boot_partition"

	if [[ "$is_uefi" == "no" ]]; then
		fatlabel "$boot_partition" BOOT
	else
		fatlabel "$boot_partition" EFI
	fi

	mkfs.ext4 -L ARTIX "$root_partition"
}

mount_disk() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Mounting Partitions
--------------------------------------------------------------------------------

"
	mount "$root_partition" "$target_mount_point"
	mkdir "${target_mount_point}/boot"
	mount "$boot_partition" "${target_mount_point}/boot"
}

setup_disk() {
	echo "Artix Linux is going to be installed on $chosen_disk. Do you want to continue?"
	options=("Yes" "No")
	select_option $? 1 "${options[@]}"

	case $? in
	0)
	check_uefi
	title
	part_disk
	title
	format_disk
	title
	mount_disk;;
	1) exit;;
	esac

}

install_base_system() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Installing Base System
--------------------------------------------------------------------------------

"
	basestrap "$target_mount_point" base base-devel runit elogind-runit linux-lts linux-firmware
	fstabgen -U "$target_mount_point" >> "${target_mount_point}/etc/fstab"
}

config_time() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Configuring Time
--------------------------------------------------------------------------------

"
	ln -sf "/usr/share/zoneinfo/$timezone" /etc/localtime
	hwclock --systohc
}

config_lang() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Configuring Language
--------------------------------------------------------------------------------

"
	echo -e "en_US.UTF-8 UTF-8\nen_US ISO-8859-1" >> /etc/locale.gen
	locale-gen
	echo -e "LANG=en_US.UTF-8\nLC_COLLATE=C" > /etc/locale.conf
}

config_network() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Configuring Network
--------------------------------------------------------------------------------

"
	echo "$hostname" > /etc/hostname
	echo -e "127.0.0.1\tlocalhost" >> /etc/hosts
	echo -e "::1\t\tlocalhost" >> /etc/hosts
	echo -e "127.0.0.1\t${hostname}.localdomain $hostname" >> /etc/hosts
	pacman -S --noconfirm --needed connman-runit wpa_supplicant
	ln -s /etc/runit/sv/connmand /etc/runit/runsvdir/default
}

set_root_pw() {
	title
	echo -e "$root_password\n$root_password" | passwd
}

setup_user() {
	title
	useradd -m "$username"
	echo "$username ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
	echo -e "$user_password\n$user_password" | passwd "$username"
	usermod -a -G video,audio,input,power,storage,disk,network "$username"
}

add_arch_repo() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Adding Arch Repo
--------------------------------------------------------------------------------

"
	pacman -S --noconfirm --needed artix-archlinux-support
	sed -i 's/^#ParallelDownloads = 5/ParallelDownloads = 4/' /etc/pacman.conf
	echo -e "\n[extra]\nInclude = /etc/pacman.d/mirrorlist-arch" >> /etc/pacman.conf
	echo -e "\n[community]\nInclude = /etc/pacman.d/mirrorlist-arch" >> /etc/pacman.conf
	echo -e "\n[multilib]\nInclude = /etc/pacman.d/mirrorlist-arch" >> /etc/pacman.conf
	pacman-key --populate archlinux
	pacman -Syy
}

setup_bootloader() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Setting up Bootloader
--------------------------------------------------------------------------------

"
	if [[ "$is_uefi" == "no" ]]; then
		pacman -S --noconfirm --needed grub os-prober
		grub-install --target=i386-pc "$target_device"
	else
		pacman -S --noconfirm --needed grub os-prober efibootmgr
		grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id="$hostname"
	fi
	grub-mkconfig -o /boot/grub/grub.cfg
}

install_microcode() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Installing Microcode
--------------------------------------------------------------------------------

"
	proc_type=$(lscpu)
	if grep -E "GenuineIntel" <<< "$proc_type"; then
		echo "Installing Intel microcode"
		pacman -S --noconfirm --needed intel-ucode
	elif grep -E "AuthenticAMD" <<< "$proc_type"; then
		echo "Installing AMD microcode"
		pacman -S --noconfirm --needed amd-ucode
	fi
	grub-mkconfig -o /boot/grub/grub.cfg
}

install_graphics() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Installing Graphics Drivers
--------------------------------------------------------------------------------

"
	if lspci | grep -E "NVIDIA|GeForce"; then
		pacman -S --noconfirm --needed nvidia nvidia-utils mesa xf86-video-nouveau
		nvidia-xconfig
	elif lspci | grep 'VGA' | grep -E "Radeon|AMD"; then
		pacman -S --noconfirm --needed mesa mesa-utils amdvlk vulkan-mesa-layers radeontop libva-mesa-driver mesa-vdpau
	elif lspci | grep 'VGA' | grep -E "Intel"; then
		pacman -S --noconfirm --needed mesa mesa-utils vulkan-intel vulkan-mesa-layers intel-gpu-tools libva-intel-driver
	fi

}

postinstall_clean() {
	title
	echo -ne "
--------------------------------------------------------------------------------
                        Cleaning after installation
--------------------------------------------------------------------------------

"
	umount -R "$target_mount_point"
	echo -ne "
--------------------------------------------------------------------------------
          Installation is done. Please Eject Install Media and Reboot
--------------------------------------------------------------------------------

"
}

select_option() {

	# little helpers for terminal print control and key input
	ESC=$( printf "\033")
	cursor_blink_on()  { printf "%s[?25h" "$ESC"; }
	cursor_blink_off() { printf "%s[?25l" "$ESC"; }
	cursor_to()        { printf "%s[%s;%sH" "$ESC" "$1" "${2:-1}"; }
	print_option()     { printf "%s   %s " "$2" "$1"; }
	print_selected()   { printf "%s  %s[7m $1 %s[27m" "$2" "$ESC" "$ESC"; }
	get_cursor_row()   { IFS=';' read -sdR -p $'\E[6n' ROW COL; echo "${ROW#*[}"; }
	get_cursor_col()   { IFS=';' read -sdR -p $'\E[6n' ROW COL; echo "${COL#*[}"; }
	key_input()         {
		local key
		IFS= read -rsn1 key 2>/dev/null >&2
		if [[ $key = ""      ]]; then echo enter; fi
		if [[ $key = $'\x20' ]]; then echo space; fi
		if [[ $key = "k" ]]; then echo up; fi
		if [[ $key = "j" ]]; then echo down; fi
		if [[ $key = "h" ]]; then echo left; fi
		if [[ $key = "l" ]]; then echo right; fi
		if [[ $key = "a" ]]; then echo all; fi
		if [[ $key = "n" ]]; then echo none; fi
		if [[ $key = $'\x1b' ]]; then
			read -rsn2 key
			if [[ $key = [A || $key = k ]]; then echo up; fi
			if [[ $key = [B || $key = j ]]; then echo down; fi
			if [[ $key = [C || $key = l ]]; then echo right; fi
			if [[ $key = [D || $key = h ]]; then echo left; fi
		fi
	}
	print_options_multicol() {
		# print options by overwriting the last lines
		local curr_col=$1
		local curr_row=$2
		local curr_idx=0

		local idx=0
		local row=0
		local col=0

		curr_idx=$(( curr_col + curr_row * colmax ))

		for option in "${options[@]}"; do

			row=$(( idx / colmax ))
			col=$(( idx - row * colmax ))

			cursor_to $(( startrow + row + 1 )) $(( offset * col + 1 ))
			if [[ $idx -eq $curr_idx ]]; then
				print_selected "$option"
			else
				print_option "$option"
			fi
			((idx++))
		done
	}

	# initially print empty new lines (scroll down if at bottom of screen)
	for opt; do printf "\n"; done

	# determine current screen position for overwriting the options
	# local return_value=$1
	local lastrow=$(get_cursor_row)
	local lastcol=$(get_cursor_col)
	local startrow=$(( lastrow - $# ))
	# local startcol=1
	# local lines=$( tput lines )
	local cols=$(tput cols)
	local colmax=$2
	local offset=$(( cols / colmax ))

	# local size=$4
	shift 4

	# ensure cursor and input echoing back on upon a ctrl+c during read -s
	trap "cursor_blink_on; stty echo; printf '\n'; exit" 2
	cursor_blink_off

	local active_row=0
	local active_col=0
	while true; do
		print_options_multicol $active_col $active_row
		# user key control
		case $(key_input) in

			enter)  break;;

			up)  (( active_row-- ));
				if [[ "$active_row" -lt 0 ]]; then active_row=0; fi;;

			down)  (( active_row++ ));
				if [[ $(( ${#options[@]} % colmax )) -ne 0 ]]; then
					if [[ "$active_row" -ge $(( ${#options[@]} / colmax )) ]]; then active_row=$(( ${#options[@]} / colmax )); fi
				else
					if [[ "$active_row" -ge $(( ${#options[@]} / colmax -1 )) ]]; then active_row=$(( ${#options[@]} / colmax -1 )); fi
				fi;;

			left)  (( active_col = active_col - 1 ));
				if [[ "$active_col" -lt 0 ]]; then active_col=0; fi;;

			right)  (( active_col = active_col + 1 ));
				if [[ "$active_col" -ge "$colmax" ]]; then active_col=$(( colmax - 1 )) ; fi;;

		esac
	done

	# cursor position back to normal
	cursor_to "$lastrow"
	printf "\n"
	cursor_blink_on

	return $(( active_col + active_row * colmax ))
}

export -f title
export -f config_time
export -f config_lang
export -f config_network
export -f set_root_pw
export -f setup_user
export -f add_arch_repo
export -f setup_bootloader
export -f install_microcode
export -f install_graphics

start_install
install_base_system
title
artix-chroot "$target_mount_point" bash << '_exit'
config_time
config_lang
config_network
set_root_pw
setup_user
add_arch_repo
setup_bootloader
install_microcode
install_graphics
_exit
postinstall_clean

exit 0
